languageCode: fr
languageName: Français
defaultContentLanguage: fr
title: Fork_Wasselonne
theme: paged.js-book
author:
  name: Timothé Jeanne
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
