name = "paged.js-book"
license = "GPL-3.0-only"
description = "Paged.js Hugo theme to create PDF in the browser"
author = "Timothé Jeanne"

[module]
  [module.hugoVersion]
      extended = false
      min = "0.64.0"
      max = ""
  [[module.imports]]
      path="github.com/jygastaud/hugo-microtypo/microtypo"
      disable=false
[params]
  pointMedian = true